### ISSUE TITLE
preview does weird HTML thing

### ISSUE THREAD

**Issue by raingloom** [Plume-org/Plume#24]
this is what I see on https://baptiste.gelez.xyz/ :
```
Making Plume Nicer

<p>I started working on a nicer interface for Plume. I'm not designer so it is not perfect, and there is a lot to do (I don't even know if it behaves correctly on mobile for example), ……
```
it is a preview for the following post: https://baptiste.gelez.xyz/~/PlumeDevelopment/making-plume-nicer/

**Comment by BaptisteGelez** [comment]
Yes, actually we have to show the HTML, because if we truncate non-escaped HTML it may result in non closed tags which could completely break the layout. But it is clearly something that needs to be changed.

I think we would need to have `subtitle` field for each post, which would be displayed when listing them instead of this ugly preview (and on the post page itself of course).

**Comment by fdb-hiroshima** [comment]
There was a regression introduced on this at some point. I'm gonna search for when it append and try to fix it
