### ISSUE TITLE
Change the logo from configuration

### ISSUE THREAD

**Issue by BaptisteGelez** [Plume-org/Plume#273]
We should have all the submitted logos in the repository, and the possibility to change the one that will be displayed with a `PLUME_LOGO` (or something similar) environment variable.

Plume version (and/or commit): 0.2.0

**Comment by BaptisteGelez** [comment]
Marking this as blocked until #161 is closed.

**Comment by trwnh** [comment]
I was thinking more along the line of inlining the logo directly into the HTML, instead of simply linking to it? In other words, allow admins to dynamically select a PNG or an SVG, and if it is a PNG, then wrap it in an `<img>` tag, and if it is an SVG, then include it directly (after sanitizing it and adding a class/id).

An example I've made: https://github.com/trwnh/plumeLogos/blob/master/sampleSVG.html uses plumeFeather.min.svg and plumeParagraphs.min.svg directly within the HTML, which allows for styling the logo with CSS :)

Specifically, an admin panel would allow admins to set the size, fill, background, and even the stroke width as desired!

**Comment by BaptisteGelez** [comment]
Yeah, that would be great, and it could be possible to either include SVG or an <img> tag with askama.

**Comment by fdb-hiroshima** [comment]
We use more than one logo (filled or not), and the manifest.json advertise many different picture sizes. How should we handle that with custom logos?
My best idea at the moment would be to ask for a `PLUME_LOGO`, which disable all builtin, and an optional `PLUME_LOGO_FAVICON` for the second logo, which default to the first if none provided, as well as reading any `PLUME_LOGO_{int}` and use them for the manifest.json

**Comment by BaptisteGelez** [comment]
@fdb-hiroshima Sounds good to me. :+1:
