### ISSUE TITLE
Subtitle appears as CW on Mastodon

### ISSUE THREAD

**Issue by averageunicorn** [Plume-org/Plume#429]
I see that follow issues that I noticed are already fixed – great work! Anyway, when I imported a Plume post to my mastodon instance by copypasting the url, I noticed that it doesn't look great:

The field that is labeled "subtitle" and appears as such in a Plume post becomes a CW in Mastodon. Either that is the wrong behaviour, in that case I suggest not making a CW and instead formatting as "[Title]. [Subtitle]" or "[Title][newline][Subtitle]".

Or it is intended, in this case I think that the field on Plume should be renamed to something like "Content note" or "Content warning" to make it clearer what will happen with it in federation.

Plume version (and/or commit): 0.2.0

**Comment by fdb-hiroshima** [comment]
This is also an issue with Pleroma, anytime I refer to Mastodon later, this also includes Pleroma.
The subtitle (which is intended to be that) is sent as a the `summary` property. Sadly, Mastodon uses this field for content warning. I don't think what we are doing is incorrect, but the specs are permissive enough to make two valid implementation more or less incompatible. There are a few way this could end :
 - Mastodon using title as CW when there is one, instead of always using the summary (probably the best solution)
 - Removing subtitles or changing what we expect it to be
 - Us inverting what we are sending to bend around the issue (would work, but would also be ugly), as title as CW seems more logical
 - Multiplexing fields, with newline, which would work too, but as we are not sending `Notes` (toots) but real `Articles`, I'm not a big fan.

These 2 last solutions feels like dirty fixes to a more profound issue more than proper a proper solution.

This could be fixed in a matter of second if we choose option 3, and not much more for 4, but I think we should speak of it with other actors before rushing into a sub-optimal solution

**Comment by trwnh** [comment]
I think this is more accurately a bug in Mastodon -- CW should not be applied when `sensitive` is not set to true. https://github.com/tootsuite/mastodon/issues/8609

**Comment by BaptisteGelez** [comment]
The issue has been fixed in Mastodon, I think we can close here.

**Comment by averageunicorn** [comment]
Ah, sorry, thanks for explaining :)

**Comment by fdb-hiroshima** [comment]
It's no problem, actually it may have been because this issue emerged that Gargron fixed it on Mastodon.
When I'll have some time I'll open an issue on Pleroma's tracker so it's fixed there too

**Comment by zcdunn** [comment]
Pleroma displays the articles correctly. Here's a recent post from Funkwhale. 
![image](https://user-images.githubusercontent.com/7121969/51322064-695e8580-1a32-11e9-8263-197e2c50bdc4.png)

The title is at the top and linked to the article, with the subtitle and body under that.

**Comment by zcdunn** [comment]
Ok that's my bad. I thought 'Development' was a subtitle, but I see now it's a heading in the body. Sorry about that
