### ISSUE TITLE
feature: Additional Themeing: LiveJournal style etc

### ISSUE THREAD

**Issue by Shleeble** [Plume-org/Plume#537]
I would like a full theme templating engine to be used to allow people to theme instances at a minimum, but with the goal of letting users modify their blogs.

I am a huge fan of the LiveJournal style themes and as a side project might work to fork the theme to reach these goals.

**Comment by marek-lach** [comment]
> I would like a full theme templating engine to be used to allow people to theme instances at a minimum, but with the goal of letting users modify their blogs.
> 
> I am a huge fan of the LiveJournal style themes and as a side project might work to fork the theme to reach these goals.

Theming is already planned for a future release. Basic groundwork for it is already laid out in the code, which is why you can already see that the background of the blogs is a light gray, while post listing and tags is a darker gray,  links are purple and so on. 

But features like user/blog/domain management, moderation tools, editor and federation improvements are more fundamental to the project than theming at this stage.

_Related to_ #403

**Comment by BaptisteGelez** [comment]
Would what is described in #40 work for you?

**Comment by Shleeble** [comment]
I'll close this as a dupe.. and If I reach something I can PR, you'll get that separately :)
