### ISSUE TITLE
Can not upload avatar image: Couldn't copy upload

### ISSUE THREAD

**Issue by Porrumentzio** [Plume-org/Plume#823]
We have built a new Plume instance but we're unable to upload avatar images: `Couldn't copy upload`

#191 seems similar, but I think it's not the same

- **Plume version:** 0.4.0
- **Operating system:** Manjaro Linux MATE on my side
- **Web Browser:** Firefox on my side

**Comment by trinity-1686a** [comment]
I don't think it's related to 191.
If you have set `MEDIA_UPLOAD_DIRECTORY` in .env, you should verify the directory exist and the user running Plume is allowed to write in it.
If you have not, you should check for a directory named `static/media`. It used to be in git so you did not need to create it, but it appears to be missing now, if that was the issue I'll add it back so that default configuration work without need for tinkering

**Comment by marcelcosta** [comment]
Hello,

It was a problem with permissions. It has already been solved, so the issue can be closed.

Thank you!
